[package]
edition = "2021"
name = "rust_basic_todo"
version = "0.0.1"


[dependencies]
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "2.1.1", features = ["postgres", "serde_json"] }
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"

[[bin]]
name = "rust_basic_todo"
path = "./src/main.rs"