services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_app
    volumes:
      - ./pgdata:/var/lib/postgresql/
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 750M
        reservations:
          cpus: '0.25'
          memory: 500M

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - postgres
    env_file:
      - ./.env
    volumes:
      - ./:/app
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1024M
        reservations:
          cpus: '0.125'
          memory: 500M

volumes:
  pgdata: