services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_app
    volumes:
      - ./pgdata:/var/lib/postgresql/data/

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://root:password@postgres:5432/todo_app
      RUST_LOG: debug
    volumes:
      - ./:/app

volumes:
  pgdata: